### ISSUE TITLE
Monster Hunter 3,4,XX force close

### ISSUE THREAD

**Issue by rioackerman96** [citra-emu/citra-android#10]

**Comment by BreadFish64** [comment]
We need more information on the exact steps leading up to the crash.

**Comment by Lxoric** [comment]
- Loader issue

**Comment by Lxoric** [comment]
https://del.dog/CitraMH.txt

**Comment by gilberthcloverzz** [comment]
@Lxoric how to solve it?

**Comment by Lxoric** [comment]
Can't unless devs fixes those errors.

**Comment by Schplee** [comment]
Can confirm that this issue occurs in Both Generations and 4. Creating a new character, and then trying to load that new save file will cause the game to crash during the loading screen.

**Comment by SutandoTsukai181** [comment]
This was possibly fixed by #70. I can confirm that MH4U does not crash on Beta 4 when loading a new save file.

**Comment by Schplee** [comment]
Resolved by #70. Verified that MH4U and Generations no longer crash
