### ISSUE TITLE
citra_log

### ISSUE THREAD

**Issue by scuba-steve12** [citra-emu/citra-android#100]
would there be any way this option can be brought across to the android version... would be helpful for helping any one that has issues on the android platform

**Comment by AndresNorm** [comment]
If im not wrong..
Its in the log folder.
🤔

**Comment by scuba-steve12** [comment]
this is all it says...
![Screenshot_20200528-155041](https://user-images.githubusercontent.com/65983989/83157031-0c311480-a0fb-11ea-9f06-041448e91847.jpg)

**Comment by AndresNorm** [comment]
What were you looking for?

**Comment by FearlessTobi** [comment]
The Android version already has the same logging functionality as the Desktop one.
