### ISSUE TITLE
Pokemon X Low Fps

### ISSUE THREAD

**Issue by jolomoto** [citra-emu/citra-android#102]
im using official citra

my pokemon x is very lag and low fps below 20
but some 3ds game are fine

my phone is redmi note 5 pro snapdragon 636

and some of the other issues are  missing textures, missing and incorrect shaders, low fps.

but when i use mmj citra 20200428 with 60fps codes its good
but the audio is bad

![Screenshot_2020-05-29-03-02-08-025_org citra citra_emu](https://user-images.githubusercontent.com/65868960/83182456-f7836980-a158-11ea-9150-6048c285f2b0.jpg)

[citra_log.txt](https://github.com/citra-emu/citra-android/files/4697686/citra_log.txt)

**Comment by FearlessTobi** [comment]
We don't accept generic low FPS issues here. Please ask for support on our forums or our Discord server.
