### ISSUE TITLE
heat and performance

### ISSUE THREAD

**Issue by scuba-steve12** [citra-emu/citra-android#116]
hi all,

i dont know if your looking in to it or cant be done, was just thinking this might help with the performance and the heat ?
![Screenshot_20200530-120823](https://user-images.githubusercontent.com/65983989/83326879-491e1800-a26f-11ea-8968-a851ac647448.jpg)
![Screenshot_20200530-120817](https://user-images.githubusercontent.com/65983989/83326883-4fac8f80-a26f-11ea-9935-e09d15d8a612.jpg)

**Comment by FearlessTobi** [comment]
I'm not sure what you're trying to tell us with this. Also we don't support unofficial builds here.

**Comment by scuba-steve12** [comment]
was trying to say if the emu is using more cores or the load was spaced over more core's there would not be as much heat, as i use both... as i dont know if the offical build uses more then one core for every thing...

**Comment by Lxoric** [comment]
It depends on the load. Mostly if you run Citra official it will take all the work to GPU and CPU(Big cores) so changing about it will reduce performance of the emulation. Unofficial and Official are not tracking the same way.
