### ISSUE TITLE
Cannot load working PC save on Android

### ISSUE THREAD

**Issue by rheard** [citra-emu/citra-android#119]
I created a new save for Omega Ruby on Android and was able to load it up on PC with no issue.

However I created a save on PC and when I transfer it over to Android, I get a save data corruption error. The save works fine on PC.

Attaching the user folder from the PC version and the logs folder from Android. I have tried this with and without cheats.
[log.zip](https://github.com/citra-emu/citra-android/files/4706302/log.zip)
[user.zip](https://github.com/citra-emu/citra-android/files/4706303/user.zip)

My phone is a Samsung Galaxy S10+, US version.

**Comment by BreadFish64** [comment]
Pokemon stores some information in extdata as well, please try transferring that and see if you get the same error.

**Comment by rheard** [comment]
> Pokemon stores some information in extdata as well, please try transferring that and see if you get the same error.

I transferred over the entire user folder. Cheats, config, and yes, the entire sdmc folder.

**Comment by rheard** [comment]
This issue turned out to be because FileZilla has an option to transfer as "ASCII" or "Binary", or "Auto" which is the default

It must've been detecting the saves as "ASCII" because any 0x0A character was converted to 0x0D0A instead, and the file sizes were messed up

Fixing this setting in FileZilla resolved my issue. Closing
