### ISSUE TITLE
Speed issues on Pokémon Ultra Sun; request for inclusion of AR cheats

### ISSUE THREAD

**Issue by aecarvalho** [citra-emu/citra-android#12]
One of the things I immediately noticed on installing the app is that there's no way to disable game audio which also stutters in game because game speed rarely reaches over 85% on a Snapdragon 845 phone, would be great to see more optimization done on the graphics like the Citra emulator by Zhang Wei, which also incidentally has a cheats section for AR codes which works beautifully in game, hope you address these issues and also have a way to move/position the upper and lower screens and edit screen size if possible because the lower screen looks overly magnified and pixelated in comparison to the upper screen. Lastly I'd also request to add AR cheats if possible, Citra is beautiful on the PC because of it.
I've added a screenshot of both Citra apps side by side.

Thanks and regards,
Alwyn.
![Screenshot_20200523-152926685](https://user-images.githubusercontent.com/60945000/82728204-b3353b00-9d0c-11ea-9350-f8fe2c3e47d5.jpg)
![Screenshot_20200523-153701025](https://user-images.githubusercontent.com/60945000/82728222-bb8d7600-9d0c-11ea-8154-fd8f4e3f3cab.jpg)
![Screenshot_20200523-154855757](https://user-images.githubusercontent.com/60945000/82728264-f42d4f80-9d0c-11ea-8895-3d74514fb8bb.jpg)
![Screenshot_20200523-154900400](https://user-images.githubusercontent.com/60945000/82728283-0c04d380-9d0d-11ea-9d34-efc13053b4d2.jpg)

**Comment by BreadFish64** [comment]
> One of the things I immediately noticed on installing the app is that there's no way to disable game audio
Noted, I have a volume slider that didn't make it into the final app
> would be great to see more optimization done on the graphics like the Citra emulator by Zhang Wei
We can definitely look through his code for useful optimizations, but things like texture loading hacks and "skip slow draw" don't meet our standards. We are aware that some devices are slow.
Cheats will most likely be addressed in the future, we are aware that the current app does not have feature parity with desktop.

Closing this because it should have been multiple issues. And most of them are not useful to the developers.

**Comment by aecarvalho** [comment]
Interesting... I didn't activate Texture Loading Hacks in settings, I'm not sure of which settings "skip slow draw" would include anyway. I could raise it as multiple issues if you like 😅 I just felt it would be better to put it in one single stretch.

I'd still prefer an audio on/off switch so that only the video without the audio is rendered, might increase the FPS and speed, this is Snapdragon 845 which has 2.8GHz(×4)+1.8GHz(×4) and a good enough Adreno GPU, the difference in speed of both emulators is 3FPS and 10% speed approximately indicates it's not a device specific issue.

Anyway thanks for reading the issues.
