### ISSUE TITLE
missing textures

### ISSUE THREAD

**Issue by jolomoto** [citra-emu/citra-android#125]
pokemon ultra moon v 1.2
the official release is more accurate but slow, while the other one (citra mmj) is faster but less accurate.
i enabled the accuarate shader but still like this.

redmi note 5 pro snapdragon 636

[citra_log.txt](https://github.com/citra-emu/citra-android/files/4708414/citra_log.txt)

![Screenshot_2020-06-01-04-53-15-367_org citra citra_emu](https://user-images.githubusercontent.com/65868960/83362466-0de12d80-a3c4-11ea-9a84-bfbbd37ec9b8.jpg)

**Comment by Lxoric** [comment]
For turning on accurate shader fix this. Using the same specs SDM636
