### ISSUE TITLE
Grey screen in Hyrule Warriors Legends 

### ISSUE THREAD

**Issue by MajorasMaks** [citra-emu/citra-android#139]
In Hyrule Warriors Legends I get grey flickering all over the screen, but this mostly only happens on lava battlefields.

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.

**Comment by MajorasMaks** [comment]
But that it is an issue

**Comment by FearlessTobi** [comment]
But you didn't follow our issue template at all for like the 100th time.

**Comment by MajorasMaks** [comment]
K sorry, its quite complicated
