### ISSUE TITLE
Entire screen is not used in the 2520x1080 Xperia 5

### ISSUE THREAD

**Issue by tovarishes** [citra-emu/citra-android#141]
The entire screen is not used in the Xperia 5. 
![Screenshot_20200606-142945](https://user-images.githubusercontent.com/17121747/83944358-3b363d00-a803-11ea-94ba-fea4f16a779a.png)

**Comment by FearlessTobi** [comment]
https://github.com/citra-emu/citra-android/pull/143 PRed a potential fix
