### ISSUE TITLE
Latest (7966294b6} release ignores Enable limit speed checkbox

### ISSUE THREAD

**Issue by tovarishes** [citra-emu/citra-android#144]
The latest play store release from 6th June 7966294b6 doesn't react to the Enable limit speed checkbox like it used to in previous releases running at 100+ fps.

**Comment by SutandoTsukai181** [comment]
The checkbox is not ignored, but emulation is always limited to 100% and cannot get any higher, even if you enable speed limit and set it to 200%. This issue happens only in Beta 9.
