### ISSUE TITLE
An option for new 3DS mode (Feature Request)

### ISSUE THREAD

**Issue by saintbepis** [citra-emu/citra-android#148]
Was wondering if a option for new 3DS mode could be made in settings.

**Comment by AndresNorm** [comment]
This is an issue tab.

**Comment by saintbepis** [comment]
> This is an issue tab.
> 

There are other feature requests on this issue tab

**Comment by FearlessTobi** [comment]
What value would this provide to the end-user?

**Comment by saintbepis** [comment]
> What value would this provide to the end-user?

Some games support the new 3ds but will play in old 3ds mode on citra, like in shin megami tensei 4 apocalypse you get a bigger view of portraits on a new 3ds

**Comment by FearlessTobi** [comment]
New 3ds mode is enabled by default in Citra Android. 
If some games don't work as intended, please check if the problem also exists in the Desktop version and if yes, please open an issue there.
