### ISSUE TITLE
Optimizing Plan for Kirin CPU and Mali Gpu

### ISSUE THREAD

**Issue by c745038950** [citra-emu/citra-android#149]
Hi, may I ask do you have plan for optimization of Mali GPU based Phones? And when will you start?
My phone is HUAWEI Honor 20 pro, with Kirin 980 and Mali-G76 720MHz GPU.

For example, when emulating Metal Max 4, it can only reach around 10fps when in the world map.(when going into towns, fps goes up to 30)
Some other games have the same issue, cannot reach 100% speed. 
As you know, HUAWEI's Kirin Cpu enjoys large market share in the world, especially in China, we do hope we can have a better emulating experience from Citra.
Hope to receive your answer in Comment. 

Thank you for your hard work and great support.

**Comment by FearlessTobi** [comment]
Sorry, but I'll be closing the issue for now as it's not really actionable.
Some chipsets just have subpar drivers or performance. We can't do much about this.
I'm sure general speed improvements will come in the future but probably not for specific vendors but for all devices.
