### ISSUE TITLE
Crashing suddenly at times when using Pokémon Ultra Sun unlike issue #46

### ISSUE THREAD

**Issue by aecarvalho** [citra-emu/citra-android#168]
This doesn't happen frequently but it is annoying when it does, this time I just tried using a Max Revive on a fainted Shellder while in battle with a wild Nosepass and suddenly the app just reset to games list.
I'm on Citra version 3608cb90b from Play Store, running on Poco F1 with Snapdragon 845, 6GB RAM, I have mostly kept all the settings to default, speed limit is enabled and at 100%, graphics: linear filtering and accurate shader multiplication are disabled, rest everything was left untouched.

**Comment by FearlessTobi** [comment]
Could you try to get a log?

**Comment by aecarvalho** [comment]
Actually I tried checking and it's possible that it's a RAM issue because other apps force close on getting overworked as well
