### ISSUE TITLE
Dragon quest 8 is unplayable.

### ISSUE THREAD

**Issue by Cordlinam7** [citra-emu/citra-android#175]
Dragon quest 8 doesnt work. Once you get to port prospect it's impossible to progress any further. The game doesnt seem to realize I've taken a picture of what's his face. Literally I took 100 pictures of him and hes clueless so I cant progress and wasted several hours getting to this point. Yet your compatibility list says it works great. Very very wrong. I'll happily become a patron right now if you can offer a working solution.

**Comment by FearlessTobi** [comment]
Could you please provide a log file as requested in our issue template?

**Comment by Cordlinam7** [comment]
Actually I figured it out. It was a hardware rendering issue. I had to turn rendering off, take the picture and save the game. Then it registered. Great emulator. I will become a patron on payday.
