### ISSUE TITLE
[FEATURE REQUEST] Cheat support

### ISSUE THREAD

**Issue by IAmLoaf21** [citra-emu/citra-android#187]
Title says it all I guess?? I mean cheats like AR codes and stuff, if it's possible. Cheers, devs!

**Comment by FearlessTobi** [comment]
Duplicate of https://github.com/citra-emu/citra-android/issues/27. 
By the way, I already have the UI for cheats in a half-working state. I only need to clean the code up and do some testing to fix outstanding issues.
