### ISSUE TITLE
Can you support launching games from a front end?

### ISSUE THREAD

**Issue by rayors** [citra-emu/citra-android#188]
Can you support launching games from a front end?

**Comment by FearlessTobi** [comment]
I'm not sure what you mean by this request, as you haven't given any explanation at all.
Therefore I'll close it for now.

**Comment by rayors** [comment]
Dig frontend

**Comment by b-anthony-aguilar** [comment]
I would also like to request this feature. Some people like to run their games from a dedicated frontend app such as Dig or ARC Browser. Currently Citra is the only emulator I use that does not support launching from a frontend app.
