### ISSUE TITLE
CPU clock speed

### ISSUE THREAD

**Issue by yuraPIMENOV** [citra-emu/citra-android#192]
There is a feature CPU Clock Speed on the PC version of Citra. But on Android it is missing. Without it, you can't accelerate games that run slowly by default.

**Comment by Tyaisurm** [comment]
@yuraPIMENOV I already made [issue post about this](https://github.com/citra-emu/citra-android/issues/190) few days ago. If you *really* want to edit it right now, you can try editing the configuration file manually.

**Comment by FearlessTobi** [comment]
Closed as duplicate.
