### ISSUE TITLE
[Feature request] LeiaLoft 3D support

### ISSUE THREAD

**Issue by red4v** [citra-emu/citra-android#194]
LeiaLoft devices have glasses-free 3D screens (and what they call 4V†), but to use 3D mode the app needs to be built using their SDK ([download link](https://s3.amazonaws.com/leia-services-e5a1/wp-content/uploads/20180519204016/LeiaLoft_NativeAndroid_SDK_2018-04-01.zip) and [documentation](https://docs.leialoft.com/developer/android-sdk/leia-creative-toolkit)).
Only 2 devices have these screens though (RED Hydrogen and Lume Pad) making this feature quite niche, so a rough untested branch, or even just some pointers on how to implement this myself (mind you, I have virtually no programming skills) would be greatly appreciated.

†4-View mode, which is 3D but with additional far left and far right frames giving it a holographic effect (like a shiny trading card). Most of the documentation assumes you're implementing 4V, but you can do just normal 3D.

**Comment by jakedowns** [comment]
following along cause i think this would be awesome

**Comment by jakedowns** [comment]
@red4v I've built a version of the app that supports Lume Pad!
https://github.com/jakedowns/citra-android/releases/tag/beta-15.1

I don't have a RED Hydrogen, but if I did, I'd try to get it working there too ;)

**Comment by jakedowns** [comment]
according to https://twitter.com/eminus/status/1428825017870024704
it works on the Hydrogen One as well?!

**Comment by jakedowns** [comment]
Well, I guess since Leia's SDK is closed source, it won't ever be possible to merge it in due to GPL. So maybe this Issue should be closed now. However, if any of the maintainers are ever interested in merging my fork in, let me know. The interlacing shader is simple. However the library used to toggle the LitByLeia display backlight between 2D and 3D mode is precompiled and closed source. Who knows, maybe some day @leiainc will make their code opensource.

**Comment by SonofUgly** [comment]
Yep can confirm it works on Hydrogen, good job. Pretty neat being able to play Citra on a handheld, with gyro, and glasses free 3D.

Though getting heavy ghosting/double image at around 10% depth and above, not sure if it's something that needs tweaked or citra just allows for really extreme depth.

**Comment by jakedowns** [comment]
awesome! thats great to hear.

ill work on seeing if i can get the disparity dialed in
i might also see about adding a depth of field option

**Comment by red4v** [comment]
> @red4v I've built a version of the app that supports Lume Pad!
> https://github.com/jakedowns/citra-android/releases/tag/beta-15.1
> I don't have a RED Hydrogen, but if I did, I'd try to get it working there too ;)

Nice! It looks beautiful. And I think you just increased the amount of games that can be played in 3D on LeiaLoft devices by like 50x lol. Have you thought about doing other emulators, I believe PPSSPP android also has 3D.

Anyway, guess I'll close this due to the licensing issues. Shame about that, hopefully they opensource it, but at least people can use your build until then.

**Comment by jakedowns** [comment]
Thanks @red4v feel free to follow me on github or twitter.com/jakedowns i'll post updates there as i do more in this realm.
I'm also pretty active on the leia forums.

i just recently added support to the VirtualVirtualBoy emulator in a forked branch (hoping to merge that into mainline soon) https://github.com/jakedowns/vvb/releases

i'm looking into other quick integrations, so i'll definitely take a look at PPSSPP, thanks for the recommendation. 

right now on my list is Dolphin, and then maybe working on performance of Citra on Android.

**Comment by jakedowns** [comment]
for anyone who finds this in the future, Citra is officially in the Leia App Store
