### ISSUE TITLE
Graphics issues 

### ISSUE THREAD

**Issue by faroukabd000** [citra-emu/citra-android#198]
I got some glitsh and textures issues especially with
-Attack on titans1&2 /weird fog and blurry image but the character is visible 90% and the game is too slow 
-Digimon redigitize (or something) /the player and his digimon look weirds (long hands, legs,necks like snakes
-the amazing spiderman2 /he is invisible but you can see blue and red color attached to the upper edge or the screen! !
-inazuma eleven go 2 /when having conversation always the back ground is red or pink
-dragon ball fusion same as inazuma
*Phone mi a3 android 10 sd 665 adreno 610 ram 3*

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord or forums for support requests.
Thanks
