### ISSUE TITLE
android 11 

### ISSUE THREAD

**Issue by scuba-steve12** [citra-emu/citra-android#206]
hi all, 
keep up the great work.. i'm looking to change from Android 10 to Android 11 beta on my oneplus 7 pro 5g. but i;m not sure if citra will run on it as i know the filing system and the driver support is different, can you let me know if it will or will there be an update/version for Android 11

**Comment by FearlessTobi** [comment]
Citra should work just fine on Android 11.
Also please note that this issue tracker is NOT the place to ask questions or get support.
Please use our forums or Discord for that.
