### ISSUE TITLE
beta13 Load State error

### ISSUE THREAD

**Issue by android-1995** [citra-emu/citra-android#207]
upgrade from beta12 to beta13

![Screenshot_2021-01-31-09-08-44-203_org citra citr](https://user-images.githubusercontent.com/35674533/106371827-05525400-63a4-11eb-88e5-ef1497168d1a.jpg)

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use the Citra forums or our Discord for support requests.
Closing
