### ISSUE TITLE
It Not Working On Armv7 Devices

### ISSUE THREAD

**Issue by TheChadda** [citra-emu/citra-android#214]
So win i trie to manliy install Citra it says its not compatible with my device

Device Info:

RAM: 976MB
Internal Storage: 10.4GB
Android Version :  Pie (9)
CPU Cores: 4 (All Or Compatible With Armv7)
Device: Amazon Kennel 7 2019
Citra Version: a6860a9 (Beta 14)

and yes i use a amazon kennel

**Comment by SachinVin** [comment]
32 bit devices are not supported, you need a 64 bit device to use Citra
