### ISSUE TITLE
Not run

### ISSUE THREAD

**Issue by faroukabd000** [citra-emu/citra-android#22]
You said in patron the app work in lollipop as minimum target and some medium devices and yeah hell
It run only on snapdragon latest release and android.
can it be for medium devices in future? ???

**Comment by FearlessTobi** [comment]
I don't think our requirements are going to go any lower in the future.
Citra runs fine on my device that's 3+ years old.
If your phone doesn't reach the requirements, it probably won't be able to run Citra at acceptable speeds either.

**Comment by faroukabd000** [comment]
waiting for almost  2 years and what!!!!!  and finally i will buy a console!!! 
さらばだシトラーめ😡😠
