### ISSUE TITLE
Building for Android From Source with a modified Core

### ISSUE THREAD

**Issue by jakedowns** [citra-emu/citra-android#240]
I'd like to add a page to the main wiki: Building for Android From Source.

These are the notes I have so far: https://gist.github.com/jakedowns/cb7f17e4d97a79be8a6c8c4fdfc0c819

However, on my branch i'm creating, I'm including a new external library: [Leia Native SDK](https://docs.leialoft.com/developer/android-sdk/leia-creative-toolkit)

Obviously, adding a 7th StereoRender option will require me to rebuild Core

I'm curious, what settings did you use / do you recommend for running cmake against Core when targeting `ANDROID` + `ARCHITECTURE_ARM64`

is it as simple as:
```
cmake .. -DANDROID -DARCHITECTURE_ARM64 -DCMAKE_CXX_COMPILER=clang++-5.0 \
	-DCMAKE_C_COMPILER=clang-5.0 \
	-DCMAKE_CXX_FLAGS="-O2 -g -stdlib=libc++"
```

or... does Core get rebuilt when i run a gradle build in android studio?

I'm mainly a web dev, dipping my toes into the world of .cpp and Android, so forgive a potentially naïve question

Thanks for all the work you've put into getting this running on Android thus far. Very impressive.

**Comment by SachinVin** [comment]
You don't need to manually build the core, gradle should build it for you.
