### ISSUE TITLE
Question about linked library referencing libGLESv2.so

### ISSUE THREAD

**Issue by jakedowns** [citra-emu/citra-android#241]
Hello again. I'm continuing to make progress on my test of adding the LeiaNativeSDK support on my fork here:
https://github.com/jakedowns/citra-android/commit/2e42a6d26e18ba61beaebc0fb9fa2126a061dc79

I've run into an error tho: 
```
C:/Users/X/AppData/Local/Android/Sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/windows-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin\ld: warning: libGLESv2.so, needed by ../../../../../../../externals/leia_sdk/lib/arm64-v8a/libleiasdk.so, not found (try using -rpath or -rpath-link)
```

In the Leia SDK Example, they have you link `EGL` and `GLESv3`, as seen here: https://github.com/jakedowns/LeiaLoft_NativeAndroid_SDK/blob/5c161b3c9c3ce1d9fb0287b7ba0880c9859eb310/Samples/TeapotsWithLeia/more-teapots/src/main/cpp/CMakeLists.txt#L59 

I noticed in the Citra-Android repo, in the AndroidNdkModules.cmake file, you have a similar library linking going on, only it's `EGL & GLESv2`
https://github.com/jakedowns/citra-android/blob/2e42a6d26e18ba61beaebc0fb9fa2126a061dc79/CMakeModules/AndroidNdkModules.cmake#L54

I would assume, that this would be enough for libleiasdk.so to be able to load libGLESv2.so as-needed? but it appears not?

For good measure, I tried including GLESv3 in the video_core > CMakeLists file here: https://github.com/jakedowns/citra-android/blob/2e42a6d26e18ba61beaebc0fb9fa2126a061dc79/src/video_core/CMakeLists.txt#L164

and, in `video_core/renderer_opengl/renderer_opengl.cpp` I attempted to include
```
#include <EGL/egl.h>
#include <GLES/gl.h>
```
https://github.com/jakedowns/citra-android/blob/2e42a6d26e18ba61beaebc0fb9fa2126a061dc79/src/video_core/renderer_opengl/renderer_opengl.cpp#L15

still, to no avail. (wasn't sure if it only needed to be included in the .cpp file or also the .h file?)

Anyway, I could go on and on, but hopefully this is enough info that you could hopefully point me in the right direction. I'm happy to provide any more info that may be helpful. I'm also reaching out to Leia support to see if it's something they have advice for.

Thank you

**Comment by SachinVin** [comment]
Not every macro in `AndroidNdkModules.cmake` is used, your sdk might not even be linking there(I don't even know if any macro in there is used). Also consider using IRC or discord for development related questions, you can request one of the mods to grant you access for the #development channel on discord.

**Comment by jakedowns** [comment]
thanks for the feedback. I will close this. Are you on discord or IRC?
