### ISSUE TITLE
Water pokemon show white

### ISSUE THREAD

**Issue by cruzdd** [citra-emu/citra-android#243]
![Screenshot_2021-08-21-09-18-13-131_org citra citra_emu](https://user-images.githubusercontent.com/89284309/130306161-698cb1cd-560f-407b-b649-332e148d7ca2.jpg)

**Comment by cruzdd** [comment]
Let me know if someone experience this bug

**Comment by Gamemulatorer** [comment]
### Duplicate https://github.com/citra-emu/citra-android/issues/97

**Comment by hayvanloo** [comment]
Yap

**Comment by FearlessTobi** [comment]
Closing as duplicate.
