### ISSUE TITLE
Meu celular não consegue rodar 30fps em qualquer emulador citra

### ISSUE THREAD

**Issue by 89-0987** [citra-emu/citra-android#262]
Meu celular sendo um Samsung M32, não consegue fazer 30 fps no jogo pokemon X, em nenhum jogo. ja baixei todo tipo de citra, muitas versões até com 32bits, e nenhuma fez ele rodar 30 fps, mesmo tendo 128/6 gb. Meu sonho era poder jogar 3ds, mas nn consigo jogar direito. E agora giovanni?

**Comment by FearlessTobi** [comment]
This issue tracker is English-only.
Closing.
