### ISSUE TITLE
Direct Translation on ArmV8 (ArmV7) via backwards compatibility

### ISSUE THREAD

**Issue by 78Alpha** [citra-emu/citra-android#271]
Something similar to https://github.com/xerpi/vita2hos

I was looking into it a bit and was wondering if it would be possible to utilize backwards compatibility to assist in performance. I am unsure what is currently being used (assuming emulating ARM in software on ARM). This would allow the CPU more free resources since it would run natively (at least on the CPU side). Then all that would be needed is for emulation of the GPU (As with vita2hos).

If it can work like this, it should allow for a faster switch version as well (even if just though android).

**Comment by SachinVin** [comment]
It is probably not worth it, ARM64has many improvements over ARM32, that would be utilized by other parts of the emulator. There are also other thing to consider, like citra being GPU bound on android, or ARM dropping ARM32 back-compat on newer designs

**Comment by merryhime** [comment]
Some modern ARM64 CPUs do not have any 32-bit support; I find supporting this unlikely.
