### ISSUE TITLE
[Request] Revert broken commits

### ISSUE THREAD

**Issue by slambo311** [citra-emu/citra-android#275]
Just looking at the commit history makes me feel like you guys don't know how GitHub works. If there's an X on a commit, there are bugs with it. Common sense.

**Comment by slambo311** [comment]
Also, this entire repo hasn't been updated since 2021. That's a big red flag.

**Comment by SachinVin** [comment]
Ah, who would've thunk... But if you follow the big red X, it turns out it's the windows builds and not the android build that's failing... https://github.com/citra-emu/citra/actions/runs/2320256735
