### ISSUE TITLE
I Request Citra DEV Team for Multiplayer Support on Android.

### ISSUE THREAD

**Issue by The9uck** [citra-emu/citra-android#279]

**Comment by FearlessTobi** [comment]
Duplicate of https://github.com/citra-emu/citra-android/issues/109.

**Comment by The9uck** [comment]
Is it complete as I m not able to find any update in play store.
Sent from Yahoo Mail on Android 
 
  On Sat, 27 Aug 2022 at 3:26 am, ***@***.***> wrote:   


Closed #279 as completed.
