### ISSUE TITLE
Missing CIA Install UI option

### ISSUE THREAD

**Issue by FearlessTobi** [citra-emu/citra-android#28]
I'd like to be able to install CIAs from the UI, just as on the Desktop version.
One problem on Android is disk size constraints though.

**Comment by Developer-exe** [comment]
There could be an option to move the whole "citra-emu" directory to the SD card (if it's the directory where the installed CIAs are stored), which might solve the problem, but it might make the game perform worse.

**Comment by SachinVin** [comment]
Added in #76
