### ISSUE TITLE
[Monster Hunter series] All characters of shadow are not drawn

### ISSUE THREAD

**Issue by nassau-tk** [citra-emu/citra-android#280]
The shadow will drawing Citra for PC.
But, Any Android ver. will not drawing the shadows.

Citra for PC
[Windows10/Ryzen7 3800XT/RAM 32GB/GeForece3060]
![image](https://user-images.githubusercontent.com/48179091/187830007-732e2ad5-9d38-4e04-bc68-128a4a65134e.png)

Citra for Android (Official) [Not appear shadow]
[GalaxyS20/SD865/Adreno650/RAM12GB]
![image](https://user-images.githubusercontent.com/48179091/187830208-12158b82-decd-4049-a507-ed998b1ad8f2.png)

**Comment by Deka710** [comment]
android using opengl 3.2 and its missing some extension (i forgot) to render the shadow,also no vulkan renderer on Citra so no solution for this problem.

**Comment by nassau-tk** [comment]
Oh...l understood it.

Thank you!
