### ISSUE TITLE
Mali GPU poor performance 

### ISSUE THREAD

**Issue by nergzd723** [citra-emu/citra-android#3]
Mali GPU are getting poor performance in Citra, is there any way to tweak the code for better framerates? Even top Exynos phones can barely run Pokemon games, while 835 is doing fine. 

Synthetic FLOPS tests are reporting Mali's superior performance, but the emulator is proving the opposite. 

Is there anything we can do at this stage?

PS: I believe this doesn't need any logs because it's performance issue.

**Comment by ToxaGaming** [comment]
Mali GPUs lack a ton of features Adreno ones have and are therefore inferior in emulation. This has been proven with Dolphin too and there's nothing that can be done about it until the needed features are implemented by the Mali team

**Comment by BreadFish64** [comment]
While we would love for performance to be better on Mali GPUs, this isn't really a problem on our end.

**Comment by weihuoya** [comment]
change framebuffer `glBindFramebuffer` or change framebuffer attachment `glFramebufferTexture2D` kill performance on Mali GPU.

**Comment by nergzd723** [comment]
Nice, that fixes it, now the performance is acceptable on Exynos 9810 :+1: !

**Comment by indomilk** [comment]
> change framebuffer `glBindFramebuffer` or change framebuffer attachment `glFramebufferTexture2D` kill performance on Mali GPU.

How do you do that?

**Comment by indomilk** [comment]
Please reply
