### ISSUE TITLE
Plss change your minimum android version 🙏🙇

### ISSUE THREAD

**Issue by bishopgaming** [citra-emu/citra-android#32]
Plss add Android Nougat compatibility because I have a snapdragon 625 processor and I can't update my software 😢 

And I see, you already closed the issue same to my problem

There's any reason why you can't change your miminum Android version?! It's okay if doesn't good we will accept that, but we'll wish that we can also play some 3ds games so bad 🙏😢🙇

**Comment by Developer-exe** [comment]
I don't think it's going to happen any time soon (if it's going to happen at all). I have an Exynos 8890 (Snapdragon 820 counterpart) and I struggle to achieve full speed even on not-so-demanding games.

In heavier games, such as Pokémon Ultra Sun, I'm running at 20-25% speed (6-8 FPS) in the overworld, which is not playable at all.

**Comment by bishopgaming** [comment]
I saw a player playing 3ds same in my processor It can play 20-30 fps and it's playable but sadly my phone can't download because of android version

**Comment by bishopgaming** [comment]
![FB_IMG_1590313394346](https://user-images.githubusercontent.com/65847575/82750898-21016580-9de6-11ea-8bd4-a1990bac929e.jpg)
Here some footage of pokemon sun, snapdragon 626 (similar to 625)

**Comment by Lxoric** [comment]
Try updating ur android version. Ur gpu supports it but not your android version.

**Comment by JPeacekeeper** [comment]
I agree.  It's a shame to lose the ability to use the emulator due to the fact that there is no way to update the smartphone on Android 8, although this smartphone fully meets the needs of the official Citra.  I join the request. (sorry in my english).

**Comment by 7aychu23** [comment]
![Screenshot_2020-05-23-11-41-40-85_d4f2be808e8ee95dffc2e61a2b7efef4](https://user-images.githubusercontent.com/65857283/82755323-5e292000-9e05-11ea-8e66-71f561353089.png)
low fps on helio p60 T_T same to all mediatek chipset like g90t its so lag

**Comment by bishopgaming** [comment]
> I agree. It's a shame to lose the ability to use the emulator due to the fact that there is no way to update the smartphone on Android 8, although this smartphone fully meets the needs of the official Citra. I join the request. (sorry in my english).

So true we can't update the android version due inactive OTA

**Comment by JPeacekeeper** [comment]
> > I agree. It's a shame to lose the ability to use the emulator due to the fact that there is no way to update the smartphone on Android 8, although this smartphone fully meets the needs of the official Citra. I join the request. (sorry in my english).
> 
> So true we can't update the android version due inactive OTA

Yes. We can't update even installing custom firmware (because there is no such firmware).

**Comment by FearlessTobi** [comment]
Again, Android 7 is 4 years old now. Please understand that this is not considered modern hardware anymore and won't be supported by us.
