### ISSUE TITLE
Android TV not supported by Citra Android

### ISSUE THREAD

**Issue by azoreseuropa** [citra-emu/citra-android#34]
Samsung S9 works perfectly fine.. FPS is 60 for Super Mario Land 3D and Zelda Between Two Worlds. THANK YOU DEV!!

However.. I have a problem and I want to test it on Android TV so I can report to you.

I installed it using the third party and it tried to install but message said: App not installed.

**Comment by FearlessTobi** [comment]
We currently have no device to even test Android TV on, so we decided not to support it for now and the foreseeable future.

**Comment by azoreseuropa** [comment]
I guess, we will have to wait. Let's focus on Android mobile at first, I think. Thanks.

**Comment by alexanderadam** [comment]
@FearlessTobi [according to the Android TV developer documentation](https://developer.android.com/training/tv/start/start) there's also the possibility to run apps on [virtual TV devices](https://developer.android.com/training/tv/start/start) within Android Studio.
Which sounds easier anyway, doesn't it?

Or is there anything else missing? :thinking:

**Comment by FearlessTobi** [comment]
Yes, but to run Citra virtually we need to emulate it as an ARM device. 
This gives us great speeds of <5 FPS which are perfect for development :p
