### ISSUE TITLE
Chipsets other than Snapdragon

### ISSUE THREAD

**Issue by RiShu-X** [citra-emu/citra-android#35]
Hello sir.. 
Iam use phone with chipset helio G90t and game is very lag. 
Will it take a long time for the Citra Android to support chipsets other than Snapdragon?
Thanks in advance.

**Comment by ToxaGaming** [comment]
Citra already supports chipsets other than Snapdragon, the issue is with the other chipsets themselves. The Citra team are currently collecting data to see what they can improve in the emulator to make the experience for other chipsets better

**Comment by mrcmunir** [comment]
> Citra already supports chipsets other than Snapdragon, the issue is with the other chipsets themselves. The Citra team are currently collecting data to see what they can improve in the emulator to make the experience for other chipsets better

The main problem I detected Will be the requeriments in : GL_ARM_shader_framebuffer_fetch_depth_stencil 
The extensions developer for arm vendor they are not well known and many GPU  manufacturers do not support these extension.
Seems it's mandatory and enable when linker shader.

**Comment by FearlessTobi** [comment]
As Toxa said, we already support all chipsets that fulfill our requirements.
If a vendor doesn't want to implement a specific OpenGL extension that we need, there's not much we can do about it.

**Comment by mrcmunir** [comment]
@FearlessTobi I Will feedback report on these vendors but I Needed some basic test shader using GL_ARM_shader_framebuffer_fetch_depth_stencil for that.
But I don't know if everyone will be willing to listen
since I only know Adreno and Mali support this extension
On PC it is non-existent and I do not know any manufacturer that supports it.
Thanks.
