### ISSUE TITLE
Feature request: memory search

### ISSUE THREAD

**Issue by jknut** [citra-emu/citra-android#38]
Request to add memory search and rewrite values (similar to unofficial Android version)

**Comment by FearlessTobi** [comment]
This feature doesn't even exist on the official Citra Desktop as far as I'm aware.
Please open an issue in our Desktop repo first if you wish to have this implemented.

**Comment by aecarvalho** [comment]
> Request to add memory search and rewrite values (similar to unofficial Android version)

Actually it doesn't work even on the Zhang Wei Citra, I've tried editing values on Pokémon Ultra Sun without any success, just having the regular AR cheats section would be helpful.

**Comment by jknut** [comment]
It worked for me to edit gold in Bravely Default and DQ7. In one on the versions, it didn't work, but it did in an older one.
