### ISSUE TITLE
SMT Overclocked Blackscreen Bug in Android Version

### ISSUE THREAD

**Issue by robzombie91** [citra-emu/citra-android#4]
The same bug that affects this game from starting on the desktop version also affects the android version.

I would assume you'd have to add the CPU clock speed feature to get it working again

**Comment by BreadFish64** [comment]
Does this game require the CPU clock slider to work?

**Comment by robzombie91** [comment]
Yes i believe so, due to it fixing the desktop version if not finding the true culprit to why it wont boot

**Comment by FearlessTobi** [comment]
I'll close this for now as the issue also exists and is tracked on Citra Desktop.
