### ISSUE TITLE
Resident Evil Revelations Crash After Main Menu

### ISSUE THREAD

**Issue by ericsonia** [citra-emu/citra-android#56]
My Device Snapdragon 845
Android 9 (Pie)

**Comment by FearlessTobi** [comment]
So what is your phone?

**Comment by ericsonia** [comment]
> So what is your phone?

Zenfone 5z
Snapdragon 845
Android 9 (Pie)

**Comment by ericsonia** [comment]
Fixed on citra latest update 😍
