### ISSUE TITLE
New 3DS buttons (ZL, ZR) are not working

### ISSUE THREAD

**Issue by SutandoTsukai181** [citra-emu/citra-android#59]
New 3DS mode cannot be enabled from the menu, and the toggle in config.ini does nothing. Controls like ZR, ZL, and C-Stick can be enabled for the overlay but they are useless, although the C-Stick acts as a Circle Pad Pro when a game supports it.

**Comment by FearlessTobi** [comment]
N3DS mode should is enabled by default and people have been successfully able to run new 3ds games on Android.

**Comment by SutandoTsukai181** [comment]
The new controls are not working, this has been reported multiple times. ZR and ZL do nothing, while the C-Stick works *sometimes*. 

Also, the config file still states that 0 is the default value, which should've been edited.

**Comment by SutandoTsukai181** [comment]
Fixed by #104.
