### ISSUE TITLE
shin megami tensei 4 crashes right after the inita cutscene, while talking to the first npc

### ISSUE THREAD

**Issue by draxion69** [citra-emu/citra-android#62]
Game crashes on reaching a certain point after the initial cutscene, while talking to the first npc. Screen becomes white and frezes for a few seconds and force closes itself to the game selection screen.

Device - poco f1 
Processor - Snapdragon 845
Citra app - beta 2

**Comment by Perturbator666** [comment]
Fixed on Beta 3
