### ISSUE TITLE
Detective Pikachu intro video runs very slowly.

### ISSUE THREAD

**Issue by Nintynuts** [citra-emu/citra-android#66]
Citra for Android released on 23rd May 2020. Running on LG V50, Android 10.

Generally the game runs very well but the intro video runs slowly.

**Comment by FearlessTobi** [comment]
We don't accept generic "game runs slow" issues here as they are very broad and hard to debug for developers.

**Comment by Nintynuts** [comment]
Well It's specifically when it's decoding the intro FMV rather than rendering geometry, and I believe there may be a general issue with decoding video as the intro in LEGO City Undercover is even worse.
