### ISSUE TITLE
Shin megami tensei 4 crash bug

### ISSUE THREAD

**Issue by saintbepis** [citra-emu/citra-android#7]
The original shin megami tensei 4 will crash the citra app back to the game selection screen when loading a save file

**Comment by BreadFish64** [comment]
Duplicate of #4

**Comment by saintbepis** [comment]
> Duplicate of #4

Smt overclocked and smt 4 are different games

**Comment by BreadFish64** [comment]
Ah, my mistake

**Comment by saintbepis** [comment]
> Ah, my mistake

It's cool no worries

**Comment by Perturbator666** [comment]
Fixed on Beta 3
