### ISSUE TITLE
This app is incompatible with your device.

### ISSUE THREAD

**Issue by MariioCL** [citra-emu/citra-android#75]
I am trying to install the application but it tells me that my android is not compatible, I am using android 7.0. Any future plans for this?

**Comment by FearlessTobi** [comment]
Lowering our system requirements will most likely not be possible. A 4 year old phone will not be able to run games in Citra very well.

**Comment by MariioCL** [comment]
what are the minimum requirements to run the application?

**Comment by jjrush666** [comment]
Im geussing suertin phone duh
