### ISSUE TITLE
Hello,. I ma so excited for official citra on android.. 

### ISSUE THREAD

**Issue by kikikom** [citra-emu/citra-android#78]
I can play etriyan odysey, animal crossing new design smooth at 30 fps , but in case pokemon and animal crossing new leaf.. Must disable hardware shader.. And it will be lag.. But overall thankyoy i am so happy i can play etryan odisey in snapdragon 625

**Comment by FearlessTobi** [comment]
This is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.
Thanks
