### ISSUE TITLE
Fire emblem awakening and Pokémon series on sd660

### ISSUE THREAD

**Issue by septa15** [citra-emu/citra-android#82]
On FE awakening When battle animation scene, lag happen. But fps seems fine, when magic or support cast it take longer lag maybe 2 seconds or more.
On Pokémon series it's lag in some scene on map or battle but that acceptable the problem is the sound it's so terrible
Good luck team 💪

**Comment by FearlessTobi** [comment]
We don't accept generic "game runs slow" issues here as they are very broad and hard to debug for developers.
