### ISSUE TITLE
Feature Request: FMV Hack

### ISSUE THREAD

**Issue by Zyo13** [citra-emu/citra-android#86]
While I'm aware, this is primarily a feature of unofficial builds, incorporating it in the official android build would really help smooth out the emulation (provided that trying to achieve it doesn't result in unwanted bugs).

**Comment by BreadFish64** [comment]
I can't find any useful information on how this "FMV hack" actually works, but we don't introduce hacks that are detrimental to accuracy unless there's no way to achieve the same result while doing something properly.

**Comment by Zyo13** [comment]
Devs like SickC and weihouya managed to achieve them for an unofficial PC build and the unofficial android build respectively so if you guys enlist them among the official devs, they might be able to help. Just a thought (as long as you guys are not on bad terms with them for some reason).
