### ISSUE TITLE
None of the SETTINGS are being displayed

### ISSUE THREAD

**Issue by J16N** [citra-emu/citra-android#91]
Hello, after installing the app when I try to configure the general, graphics or even any settings I get a **blank white** screen.

![IMG_20200528_112231](https://user-images.githubusercontent.com/26867325/83105215-e5151b80-a0d7-11ea-9102-6bef1af20149.jpg)

![IMG_20200528_112713](https://user-images.githubusercontent.com/26867325/83105257-f827eb80-a0d7-11ea-842a-7a82cf4c090d.jpg)

![IMG_20200528_112750](https://user-images.githubusercontent.com/26867325/83105285-04ac4400-a0d8-11ea-8e1d-114ad48e4a9b.jpg)

![IMG_20200528_112817](https://user-images.githubusercontent.com/26867325/83105322-1261c980-a0d8-11ea-900b-22be8fbe917e.jpg)

_The app do detect games and can emulate it._

![IMG_20200528_112204](https://user-images.githubusercontent.com/26867325/83105445-4dfc9380-a0d8-11ea-9068-65a001ac18e9.jpg)

Here are my System Informations.

![IMG_20200528_113309](https://user-images.githubusercontent.com/26867325/83105633-a6cc2c00-a0d8-11ea-9bb5-9a2223d8a7b7.jpg)

![IMG_20200528_113239](https://user-images.githubusercontent.com/26867325/83105659-b3e91b00-a0d8-11ea-9e1b-b3ac852da29f.jpg)

![IMG_20200528_113152](https://user-images.githubusercontent.com/26867325/83105708-c6635480-a0d8-11ea-8a44-cfee1a26dc2c.jpg)

![IMG_20200528_113121](https://user-images.githubusercontent.com/26867325/83105737-d4b17080-a0d8-11ea-8b17-821da2b01925.jpg)

![IMG_20200528_113052](https://user-images.githubusercontent.com/26867325/83105775-e561e680-a0d8-11ea-9f56-5091f78dcb95.jpg)

![IMG_20200528_113020](https://user-images.githubusercontent.com/26867325/83105797-f3176c00-a0d8-11ea-89a6-68d530f7d527.jpg)

![IMG_20200528_112945](https://user-images.githubusercontent.com/26867325/83105826-01fe1e80-a0d9-11ea-97b2-b03883e43d04.jpg)

If you need any additional information, let me know in the comments. 😊

**Comment by SutandoTsukai181** [comment]
Do you have battery saving mode turned on? Please try restarting the app after turning it off.

**Comment by J16N** [comment]
@SutandoTsukai181 Thanks a lot! Without the battery saver turned on, it works. But how to make it work with battery saver turned on?

**Comment by FearlessTobi** [comment]
@SutandoTsukai181 Do you have any clue why battery saver affects this?

**Comment by SutandoTsukai181** [comment]
I have no idea. A user on Discord noticed that this fixes the problem, so I was checking if it's related or not.

**Comment by SachinVin** [comment]
Here's one potential lead / workaround I found on SO
https://stackoverflow.com/questions/35489828/fragmenttransaction-setcustomanimations-doesnt-work-when-battery-saver-is-on
