### ISSUE TITLE
Beta 4!  Black screen only

### ISSUE THREAD

**Issue by AndresNorm** [citra-emu/citra-android#93]
It seems updating to Beta 4 makes your Screen Black only
I dont know if its Per Devices, but it works from Beta 3 release.

I'll just provide my Specs...

Vivo V15 Mediatek Helio P70
Mali-G72 MP3

**Comment by FearlessTobi** [comment]
Does this happen in all of your games?

**Comment by AndresNorm** [comment]
> Does this happen in all of your games?

I just tested my other games...
And it doesn't do that...

I did a redump of my Pokemon Y game
And it works now..
But after i used the new option "install cia"
It goes black again

**Comment by FearlessTobi** [comment]
This seems like user error then. 
Please get on our Discord or make a topic on the forums so we can investigate this further.
